services:
  nginx:
    image: nginx:latest
    container_name: coasters-app-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - .docker/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - coasters-app-network
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    container_name: coasters-app-php
    environment:
      - CI_ENVIRONMENT=development
      - ENV_FILE=.env.dev
    volumes:
      - .:/var/www/html
      - .env.dev:/var/www/html/.env
    networks:
      - coasters-app-network
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: coasters-app-redis-dev
    volumes:
      - coasters-app-redis-data-dev:/data
      - .docker/redis.dev.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6380:6379"
    networks:
      - coasters-app-network

networks:
  coasters-app-network:
    driver: bridge

volumes:
  coasters-app-redis-data-dev:
